### ISSUE TITLE
Possible error message improvement

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#100]
In this expression a parameter does not exist:

`"param" : "VAR-${variant_${list_variant_numbers}[${IAMNOTEXISTING}]}_MS-${milestone_${list_milestone_numbers}[${list_milestone_index}]} value"`

JsonPreprocessor throws this exception:

`'The variable '${list_variant_numbers}[${IAMNOTEXISTING}]' is not available!'`

This is not really helpful. What exactly is not available? Is the index parameter not available? Is the index itself not available in the list? Is the list parameter not available?

If nested parameters are resolved recursively from innermost to outermost expression, I would expect, that the parser already stops at innermost expression, where `${IAMNOTEXISTING}` is not existing.

The expected error message in this case is:

`'The variable '${IAMNOTEXISTING}' is not available!'`

**Comment by test-fullautomation** [comment]
@namsonx : What is the status of this issue?

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger, Hello Thomas,

I implemented this enhancement and pushed [new commit 3ff0c76081](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/3ff0c76081c6876bde81fc900472c2c53675c44b) to stabi branch.

The test cases JPP_0256 and JPP_0258 can be active for JsonPreprocessor Selftest now.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by namsonx** [comment]
merged to develop branch
