### ISSUE TITLE
Nested ${} expression not resolved (JPP_0358)

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#109]
The test case **JPP_0358** contains a nested `${}` expression, with more opening elements (`${`) than closing elements (`}`):

`"val6"  : "ABC${p${ara}m"`

Previously the JsonPreprocessor has thrown this exception:

`Expecting value:`

The latest version of the JsonPreprocessor does not throw an exception any more, but returns:

`'ABC${param'`

That's wrong.

The expectation is an exception with error message telling about an opening and closing elements mismatch.

**Comment by test-fullautomation** [comment]
@namsonx : What is the status of this issue?

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Holger activates the test and gives feedback.

**Comment by HolQue** [comment]
Current error message is:

`list index out of range`

But expected is something like: `opening and closing elements mismatch`.

See also:

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/77#issue-1769668501

**Comment by namsonx** [comment]
Hello Holger,

I had push new commit [9a66c266a](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/9a66c266ad077492eac4c2abace6876a4fb78e60) to [stabi branch ](https://github.com/test-fullautomation/python-jsonpreprocessor/compare/develop...namsonx/task/stabi_branch)
The error message now look like below:
```
Exception: Invalid syntax! An opened or closed curly brackets are missing in value 'ABC${p${ara}m'.
           Please check value 'ABC${p${ara}m' in config file!!!
```

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Holger,
please test.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @HolQue ,
please test.
Thank you,
Thomas

**Comment by HolQue** [comment]
Hi Son,

only a tiny wish left ;-)

Please exchange:

```
Exception: Invalid syntax! An opened or closed curly brackets are missing in value 'ABC${p${ara}m'.
           Please check value 'ABC${p${ara}m' in config file!!!
```

by:

```
Exception: Invalid syntax! One or more than one opened or closed curly bracket is missing in expression 'ABC${p${ara}m'.
           Please check the configuration file of the executed test!
```

This avoids the singular/plural mismatch, avoids redundancy, and the term 'expression' is a more generic one than 'value' (because it can also be the name of a parameter).

**Comment by namsonx** [comment]
Hello @HolQue ,

I modified the error message in this case based on your comment above. With this modification of the error message, it makes test cases ```JPP_0356-(VALUE_DETECTION)-[BADCASE]```, ```JPP_0358-(VALUE_DETECTION)-[BADCASE]``` are failed (due to logout comparison).

Could you please help me modify the expectation of these test cases above to adapt with my [new pull-request](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/166) on stabi branch.

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Holger,
this can be closed, too?
Thank you
 Thomas

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
