### ISSUE TITLE
Invalid nested parameter format

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#117]
The JSON code

```
"param1" : [1,2,3],
"param2" : {"${param1}" : "value"}
```

causes the following error message:

`'Invalid nested parameter format: {"${param1}"'`

What is an invalid format in this case? This error message makes no sense. This does not help.

Expected is an error message telling, that it's not allowed to substitute parameters of composite data types in dictionary key names.

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding, I will update and handle an error message for this case.

Thank you,
Son

**Comment by HolQue** [comment]
Retest failed.

Error message changed to:

'Could not set variable '[1, 2, 3]' with value 'value'! Reason: cannot assign to literal (<string>, line 1)'!

This makes no sense.

Expected is an error message telling, that it's not allowed to substitute parameters of composite data types in dictionary key names.

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding, I will update the error message.

**Comment by test-fullautomation** [comment]
removed "fix in review" state.

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I created new commit [0ec343e007](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/0ec343e0072b2f56be86beb3180a2f7b74f6bdb6) to update the error message log as Holger mentioned.

Thank you,
Son

**Comment by namsonx** [comment]
Hello Holger,

This ticket was fixed with the latest commit on stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by namsonx** [comment]
merged to develop branch

**Comment by test-fullautomation** [comment]
solved with version 0.10.0
