### ISSUE TITLE
Another list index out of range

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#121]
In the following JSON code a closing curly bracket is missing (and the referenced parameter does not exist also).

`"param2" : "${IAMNOTEXISTING",`

This causes the following error message:

`'list index out of range'`

Why this? A list is not involved.

Expected is an error message telling about a missing closing bracket.

**Comment by HolQue** [comment]
Not related to missing brackets only.

Same error message also caused by empty expression: `"param2" : "${}"`

Without quotes around the expression `"param2" : ${}` the error message changes to

`Expecting value:`

This is misleading. It should be possible to detect empty brackets.

I would expect an error message like:

`Empty dollar operator expression (`${}`) detected in line ...`

**Comment by namsonx** [comment]
Hello Holger,

This issue was fixed in stabi branch ([namsonx/task/stabi_branch](https://github.com/test-fullautomation/python-jsonpreprocessor/tree/namsonx/task/stabi_branch))

Current error message is: 
```
Exception: Invalid nested parameter format in line: "param2" : "${IAMNOTEXISTING",
```

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

retest successful.

But please remove the term "nested" from error message:

`Exception: Invalid nested parameter format in line: "param2" : "${IAMNOTEXISTING",`

Because there is no nested parameter.

My understanding is, that this

`"${IAM${NO${TEX}IST}ING"`

would be a nesting of parameters.

**Comment by namsonx** [comment]
Hello Holger,

Thank you for the hint, I will update.

Thank you,
Son

**Comment by test-fullautomation** [comment]
removed "fix in review" state

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas and Holger,

I created new commit [6cabd822](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/6cabd822b11f9176ccf1a759978481591067fe2d) on stabi branch to update error message log, I also modified the log template of testcases ID: JPP_0350 - JPP_0354

Thank you,
Son

**Comment by test-fullautomation** [comment]
already fixed, Holger gives feedback.

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
