### ISSUE TITLE
History update requested in component documentation

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#144]
The current version of the JsonPreprocessor is 0.3.0 from 12.09.2023.

The latest entry in history belongs to version 0.2.4 from 06/2023.

Therefore the history should be updated.

**Comment by test-fullautomation** [comment]
Hi Son,
this is mandatory for 0.9.0.
Otherwise we don't get an update of the pypi repository.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas, 

I had created the commit [9945fe9b29](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/9945fe9b29648c7b5247fec74842b4da5de09e81) to update history, and it's already merged to develop branch.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

when you change history or version numbers or any other parts of the documentation you also have to rebuild the PDF document. This is done automatically when you execute the setup.py. Why is the updated PDF not checked in?

**Comment by namsonx** [comment]
Hello Holger,

Sorry, I was not aware that I have to check in PDF file. I will do it.

Thank you,
Son

**Comment by namsonx** [comment]
Hello Holger,

I checked in PDF file via the commit [c5af2f0822](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/151/commits/c5af2f082205f76ce9158f81d6d5faec69d09f67)

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved and already merged with #151
