### ISSUE TITLE
Rework of interface description requested

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#145]
Up to now I concentrated on the maintenance of the main component description. But also the interface description needs to be reworked (wording, layout, alignment with main component description). But to do this makes sense only after all planned changes in the code are done.

**Comment by namsonx** [comment]
Hello Thomas,

Could you please plan this documentation ticket for further release?

Thank you,
Son

**Comment by HolQue** [comment]
Hi Thomas,

you can assign this task to me also.

**Comment by test-fullautomation** [comment]
Hi Holger,

transferred to you.

Thank you,
 Thomas

**Comment by HolQue** [comment]
Done with
https://github.com/test-fullautomation/python-jsonpreprocessor/pull/218
