### ISSUE TITLE
make atest working with https://github.com/test-fullautomation/python-jsonpreprocessor/pull/13

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/python-jsonpreprocessor#15]
Hi Son,
my changes of
https://github.com/test-fullautomation/python-jsonpreprocessor/pull/13
affected also our json-preprocessor atest. 
Please create a pull request with the required adaptations that  json-preprocessor atest is working again.
SideEffect can have all related to paths.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

     I will update the atest of Jsonpreprocessor to adapt with your changes.

Thank you,
Son

**Comment by test-fullautomation** [comment]
very good!

**Comment by test-fullautomation** [comment]
issue is solved.
