### ISSUE TITLE
Invalid error message (1)

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#155]
The JSON code

`"par${1}am2" : "123"`

causes a returned value of a parameter with invalid name:

`{'parstr($){1}am2': '123'}`

Expected is an "_invalid parameter format_" error - because a hard coded integer value between curly brackets makes no sense.

For example:

The JSON code

`"par${...}am2" : "123"`

(also nonsense) causes

'Invalid parameter format in line: "par${...}am2" : "123"'

that is completely fine.

**Comment by namsonx** [comment]
Hello Holger, Hello Thomas,

I pushed new [commit 20b10d71dc](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/20b10d71dc36acec61d347e4d7ec64dd8746e323) to stabi branch for this ticket.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
