### ISSUE TITLE
Invalid error message (2)

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#156]
**[1]**

The JSON code

```
"testlist" : [1,2,3],
"value"    : ${testlist}[]
```
causes

`'Invalid nested parameter format: ${testlist}[]'`

I would prefer to have the "_nested_" removed (like already done in other error messages). Because the invalid expression does not contain nested parameters.

**[2]**

The JSON code

```
"testlist" : [1,2,3],
"value"    : ${testlist}[${}]
```

causes

`'Invalid nested parameter format: ${testlist}[${}] - The double quotes are missing!!!'`

Yes, also this expression is invalid (because of the empty curly brackets). But the extension ("The double quotes are missing") should be removed. Because this issue has nothing to do with missing quotes.

**Comment by namsonx** [comment]
Hello Holger,

I pushed new [commit 96e6e18d6b](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/96e6e18d6b507a5de2a0f14e951978468a11cdbf) to stabi branch for this ticket.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
