### ISSUE TITLE
Naming convention for parameter names

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#157]
The JSON code

```
"teststring-1"  : "teststring-1 value",
${teststring-1} : "${teststring-1} extended"
```

causes

`'The variable '${teststring-1}' is not available!'`

Reason is the minus character inside the parameter name.

Outcome: We need to define and publish a naming convention for parameter names.

If minus characters are allowed, the expected value is:

`{'teststring-1': 'teststring-1 value extended'}`

If minus characters are not allowed, the expected result is an error message telling about a naming convention violation.

But that the variable is not available, should not happen.

**Comment by test-fullautomation** [comment]
Hi Holger,

we should allow 
- starting with letter / capital letter / underscore / 
followed
- letter / capital letter / number / underscore "_" / dot "."
identically to the python rules.

According to this rules
```"teststring-1"  : "teststring-1 value",```
should raise an error that "-" is not allowed as part of a variable.

Now this brings me really in trouble...
On jsonpreprocessor level it is allowed to define a variable with hyphen, json has no limitations for names, even spaces should be allowed as key?
But: What is RobotFramework core doing if it reaches there?

Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

we should start with a smooth naming convention for stand alone JsonPreprocessor.

If it is necessary to strengthen this in case of the JsonPreprocessor is used in the context of RobotFramework AIO, this would be an issue for the TestsuitesManagement.

**Comment by HolQue** [comment]
Update:

Now the error message is:

`Error: 'The variable '${teststring-11}' is not available!'!`

Suddenly '11' instead of '1'. From where does the '11' come from?

**Comment by HolQue** [comment]
Still open.

**Comment by namsonx** [comment]
> Update:
> 
> Now the error message is:
> 
> `Error: 'The variable '${teststring-11}' is not available!'!`
> 
> Suddenly '11' instead of '1'. From where does the '11' come from?

Hello Holger, I pushed [new commit 2c562386eef ](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/2c562386eef16e3a973c80793890986adde0a9f3)to stabi branch to correct the error message issue above.

Hello @test-fullautomation, can we move this naming convention ticket to next release after we have a discussion about this ticket.

Thank you,
Son

**Comment by HolQue** [comment]
'`11`' issue from

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/157#issuecomment-1822774616

is solved.

**Comment by HolQue** [comment]
To answer the question in

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/157#issuecomment-1746903631

JSON code passed to JsonPreprocessor:

```
"teststring-1"  : "teststring-1 value",
${teststring-1} : "teststring-1 value new",
${teststring-1} : "${teststring-1} extended"
```

Outcome:

`Error: 'The variable '${teststring-1} ' is not available!'!`

Same JSON code - but with added scope '`params.global`' - passed to TestsuitesManagement:

```
"teststring-1"  : "teststring-1 value",
${params.global.teststring-1} : "teststring-1 value new",
${params.global.teststring-1} : "${params.global.teststring-1} extended",
```

Works fine. Value of `${teststring-1}` is: `'teststring-1 value new extended'`

Astonishing that the TestsuitesManagement works properly with code, that is not accepted by the JsonPreprocessor.

Why does the JsonPreprocessor not pass his error to the TestsuitesManagement?

Which behavior is the desired one?

**Comment by HolQue** [comment]
Cross check with asterisk inside parameter name:

**JsonPreprocessor:**

```
"teststring*1"  : "teststring*1 value",
${teststring*1} : "teststring*1 value new",
${teststring*1} : "${teststring*1} extended"
```

**TestsuitesManagement:**

```
"teststring*1"  : "teststring*1 value",
${params.global.teststring*1} : "teststring*1 value new",
${params.global.teststring*1} : "${params.global.teststring*1} extended",
```
Outcome: Both components react with error: "`Invalid parameter format in line: ...`"

**Comment by test-fullautomation** [comment]
Hi Holger,
can I close this ticket?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

some questions still not clarified:

```
Astonishing that the TestsuitesManagement works properly with code, that is not accepted by the JsonPreprocessor.
Why does the JsonPreprocessor not pass his error to the TestsuitesManagement?
Which behavior is the desired one?
```

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/157#issuecomment-1907774471

**Comment by HolQue** [comment]
Retest successful.

Both JsonPreprocessor and TestsuitesManagement are able to handle a parameter with name '`teststring-1`'

Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
