### ISSUE TITLE
Unexpected behavior when updating existing value in structure data

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/python-jsonpreprocessor#16]
Hi,

I found an issue this package when writing selftest for variant switch feature.
I tried to update and define new key for existing structure data, but it seems that existing data is overwritten by the new definition instead of updating.

Please refer my situation as below: 
- My config json file:
```
{
  "[import]": "./common/test_config_common.json",
  "params": {
    // Global parameters
    "global": {
      "[import]": "./common/params_global_common.json",
      "[import]": "./common/params_global_variant1.json"
    }
  },
  "preprocessor": {
    "definitions": {
      // FEATURE switches
      "[import]": "./common/preprocessor_definitions_common.json",
      "[import]": "./common/preprocessor_definitions_variant1.json"
    }
  },
  "Project": "variant_1"
}
```
- params_global_common.json file:
```
{
  "gGlobalIntParam" : 1,
  
  "gGlobalFloatParam" : 1.332,
  
  "gGlobalString"   : "This is a string", // just for test
   
  "gGlobalStructure": {
    "general": "general",
    "testing": 16
  }
}
```
- params_global_variant1.json file:
```
{
  "gGlobalVariant1" : "Specific global parameter for variant 1",
  "gGlobalStructure": {
    "general": "variant1"
  }
}
```

I expect that **gGlobalStructure.general** is upadated as **"variant1"** and **gGlobalStructure.testing** should be remained as **16**.
The result I got is **gGlobalStructure** variable contains only new value of **'general'**. 
```
  "gGlobalStructure": {
    "general": "variant1"
  }
```
Thank you,
Ngoan

**Comment by ngoan1608** [comment]
Hi,

As discussion with Son, the syntax to overwrite and add new element to existing param should be as below:
```
{
  "gGlobalVariant1" : "Specific global parameter for variant 1",
  "${params}['global']['gGlobalStructure']['general']": "variant1"
}
```
This feature has been mentioned in package's document:
https://github.com/test-fullautomation/python-jsonpreprocessor/blob/develop/doc/_build/latex/Json-Preprocessor.pdf

This ticket can be closed.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
yes, this is correct. Currently you  need to use the full path to address the correct item.
Proposals how to make the syntax easier are welcome!
One idea I have is to define something like namespaces which allow a kind of abbreviation.
Thank you,
 Thomas
