### ISSUE TITLE
Unfavorable error message

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#162]
The JSON code

```
"teststring" : "eins",
"teststring" : "${teststring.a.b.c}.zwei"
```

causes:
`
'The variable '${teststring__RecursiveInitialValue__1}['a']['b']['c']' is not available!'`

Yes, the variable is not available, but internal token strings like "`__RecursiveInitialValue__1`" should be avoided in error messages.

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding, I will fix it.

Thank you,
Son

**Comment by namsonx** [comment]
Hello Holger,

I pushed new[ commit 10604ce77d7](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/10604ce77d7609af4df783d296e8b41030909d9d) to stabi branch to solved this ticket.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
