### ISSUE TITLE
Invalid error message

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#163]
The JSON code

```
"teststring" : "eins",
"${teststring}___${teststring}" : "zwei"
```
causes:

`'Setting value 'zwei' for parameter 'str(eins)___str(eins)' is not permissible when substituting parameters of composite data types in dictionary key names!'`

But expected is:

`{'eins___eins': 'zwei', 'teststring': 'eins'}`

**Comment by HolQue** [comment]
Another impact:

The same code in context of TestsuitesManagement:

```
"params" : {
   "global" : {
      "teststring" : "eins",
      "${params.global.teststring}___${params.global.teststring}" : "zwei",
```

causes:

```
[ ERROR ] Loading of JSON configuration file failed!
          Reason: The variable '${params}['global']['teststring'])___str(${params}['global']['teststring']' is not available!
```

Even in case of the code has the same structure, the error messages are rather different. But I would expect that the error message coming from TestsuitesManagement gives the same statement like the error message coming from JsonPreprocessor.

The error message coming from TestsuitesManagement again contains parts of internal data structures:

`)___str(`

This should be avoided in error messages provided to users.

But nevertheless: In both cases returned values are expected, instead of error messages.

**Comment by namsonx** [comment]
Hello Holger,

I pushed new [commit c8720a9bc](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/c8720a9bc1eab6873452b32a7773c4eb48972d29) to stabi branch to fix this issue.

Thank you,
Son

**Comment by HolQue** [comment]
Issue solved in JsonPreprocessor, but not in TestsuitesManagement.

TestsuitesManagement still throws error:

```
[ ERROR ] Loading of JSON configuration file failed!
          Reason: The variable '${params}['global']['teststring']___${params}['global']['teststring']' is not available!
```

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding! I pushed the [new commit c12257b2ae](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/c12257b2ae0054a11ecb9b02b90407e724ebe274) to stabi branch to fix the issue you mention above.

Thank you,
Son

**Comment by HolQue** [comment]
Retest with latest versions not successful. Still got error message:

`The variable '${params}['global']['teststring']___${params}['global']['teststring']' is not available!`

**Comment by namsonx** [comment]
Hello Holger,

I tested, and it worked fine on stabi branch, I still not create a pull-request to develop yet.

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,
what is the status of this issue?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
