### ISSUE TITLE
Application freezes

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#164]
Test case **JPP_0207** makes the application freeze.

Code of JPP_0207:

```
// variant info
"variant_1"            : "VARIANT_1",
"variant_2"            : "VARIANT_2",
"list_variant_numbers" : [1, 2],
"list_variant_index"   : 0,
"variant_number"       : "1",
"dict_variants"        : {"variant_1" : "VARIANT_1", "variant_2" : "VARIANT_2"},
"variant_key_1"        : "variant_1",
//
"INNERMOST_VARIANT_VALUE" : "RIA",
"ARIAN"                   : "ARIAN",
"VARIANT"                 : "VARIANT",
//
// milestone info
"milestone_1"            : "MILESTONE_1",
"milestone_2"            : "MILESTONE_2",
"milestone_3"            : "MILESTONE_3",
"list_milestone_numbers" : [1, 2, 3],
"list_milestone_index"   : 1,
"milestone_number"       : "2",
"dict_milestones"        : {"milestone_1" : "MILESTONE_1", "milestone_2" : "MILESTONE_2", "milestone_3" : "MILESTONE_3"},
"milestone_key_2"        : "milestone_2",
//
"innermost_milestone_name" : "est",
"ilesto"                   : "ilesto",
"milestone"                : "milestone"

"VAR_${dict_variants.${variant_key_${variant_number}}}_MS_${dict_milestones.${milestone_key_${milestone_number}}}_param" : "value"
```

Last line is expected to be resolved to:

`"VAR_VARIANT_1_MS_MILESTONE_2_param"  :  'value'`

Maybe related to:

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/225

**Comment by namsonx** [comment]
Hello Holger,

I debugged the test case JPP_0207, and observed this issue is not related to https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/225

This issue related to "Nested ${} expression not resolved (JPP_0358)" https://github.com/test-fullautomation/python-jsonpreprocessor/issues/109

I will update a new commit to fix this issue.

Thank you,
Son

**Comment by namsonx** [comment]
Hello Holger, Hello Thomas,

This issue was fixed in lasted commit on stabi branch, and I also created [new pull-request](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/166) for this.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
