### ISSUE TITLE
Tiny wording adaption wanted

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#175]
The following error message is for sure correct, but also difficult to capture:

`''Could not substitute parameter '${param1}_${param2}_suffix'! Composite data types are not allowed. The value of parameter '${param2}' is [1, 2, 3]''!
`

I would prefer an alternative version like that:

`Found expression '${param1}_${param2}_suffix' with at least one parameter of composite data type ('${param2}' is of type 'list'). Because of this expression is the name of a parameter, only simple data types are allowed to be substituted inside.
`

**Comment by namsonx** [comment]
Hello Holger,

I pushed the change to stabi branch to update the error message log in this case, I also revised the expected exception of selftest based on the update error message log.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by namsonx** [comment]
Merged to develop branch

**Comment by test-fullautomation** [comment]
solved with version 0.10.0
