### ISSUE TITLE
Memory interferences are back

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#179]
With latest stabi branch the issue https://github.com/test-fullautomation/python-jsonpreprocessor/issues/98 is back.

Affected: JPP_0504 and JPP_0505

If JPP_0504 is commented out, JPP_0505 is passed.

If JPP_0504 is executed (currently failing), JPP_0505 also fails.

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding, I added some exception but forgot execute __reset(), that the reason Memory interferences are back.
I will push new commit to fix it.

Thank you,
Son

**Comment by namsonx** [comment]
Hello Holger,

I pushed the commit to fix this issue on stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

(JPP_0504 still fails; but this is not a topic of this issue.)

**Comment by namsonx** [comment]
Merged to develop branch

**Comment by test-fullautomation** [comment]
solved with version 0.10.0
