### ISSUE TITLE
One `$` character too much

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#190]
The code

`${dictparam}[${iamnotexisting}] : "X"`

causes

`Error: 'The variable '$${iamnotexisting}' is not available!'!`

In this error message there is one `$` character too much.

**Comment by namsonx** [comment]
Hello Holger,

This issue was solved on stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
