### ISSUE TITLE
Slicing shall be blocked

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#205]
Hi Thomas,

based on one of our latest discussions, my understanding now is that slicing shall not be supported (even in case of it's already working partially).

Therefore possibly ongoing development should be stopped.

And slicing notation inside square brackets has to cause a corresponding error message.

Reference:

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/184#issuecomment-1918354577

**Comment by test-fullautomation** [comment]
Hi Son,
as Holger writes I decided yesterday that we don't support slicing. Maybe later we will no, but not now.
Reaons:
1. first we should be free of existing issues.
2. rare use case
3. much effort to stabilize (e.g. can have nested parameters, ...

So, please create an error message in case you find a slicing operator or a negative index (e.g. `${list}[-1]`). Please consider that the negative index can be provided as parameter. E.g.  `${list}[${index}]` where the value behind `${index}` is negative.

Positive operator  `${list}[+1]` must be allowed. Currently there is a bug. This causes that the whole expression is not resolved.

Thank you,
 Thomas

**Comment by HolQue** [comment]
Self test: added JPP_1350 - JPP_1364 (topic: slicing; tests commented out)

**Comment by namsonx** [comment]
Hello Holger, Hello Thomas,

I created the commit [48eae0f0df](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/238/commits/48eae0f0dfcb813294d4aa0b4ce4199e09698b87) on stabi branch.

I aslo enabled the 2 test cases JPP_1350 - JPP_1364

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

in one of my commits I wrote: "JPP_1350 - JPP_1364". And the meaning of this is: "from JPP_1350 to JPP_1364", and not: "JPP_1350 and JPP_1364".

All further test cases between 1650 and 1364 are still commented out - and cause errors when I activate them.

But to fix the remaining aspects is for 0.12.x.

**Comment by HolQue** [comment]
Example:

`'Expression '${listParam}[:]' cannot be evaluated. Reason: Empty or special character is detected in pair of square brackets.'`

Expected: Slicing is not supported

`"testParam" : {"key" : ${listParam}[:]}`

still causes

`Expecting ',' delimiter: line 5 column 1 (char 75)'`

**Comment by namsonx** [comment]
Hello Holger,

All blocked slicing's test cases are uncovered and tested successful.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

please keep in mind that there is at least one error message active that mentions the possibility to use slices:

`'Could not set variable '${testlist}['${intval}']' with value '4'! Reason: list indices must be integers or slices, not str'`

That is misleading for the audience, because slicing shall be blocked. In this case you cannot take over the error message from Python.

**Comment by namsonx** [comment]
Hello Holger,

Could you please check error message again, I updated error message as Thomas' suggestion: https://github.com/test-fullautomation/python-jsonpreprocessor/issues/186#issuecomment-1887111574

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

I still get this error message with slicing proposed:

`Error: 'Could not set variable '${listP}['${indexP}']' with value 'newvalue'! Reason: list indices must be integers or slices, not str'!`

But "`or slices`" is not expected.

**Comment by namsonx** [comment]
Hello Holger,

I updated error message in this case.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
Released with RobotFramework AIO 0.12.0
