### ISSUE TITLE
Computation harmed by blanks

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#212]
This works:

```
"param1" : "A",
"params" : {"${param1}" : "A",
            "param2" : "B"
           }
```

Result:

`{'param1': 'A', 'params': {'A': 'A', 'param2': 'B'}}`

With a blank between curly bracket and quote, it does not work any more:

```
"param1" : "A",
"params" : { "${param1}" : "A",
            "param2" : "B"
           }
```

Result:

`Error: 'Invalid nested parameter format: { "${param1}" - The double quotes are missing!!!'!`

With line break instead of this additional blank, it works again.

Expectation: Such kind of blanks should not harm the computation.

**Comment by namsonx** [comment]
Hello Holger,

This issue was fixed on stabi branch!

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
