### ISSUE TITLE
Side effects of self assignments

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#213]
The question is: What shall be the outcome of code like this?

```
"param" : "value",
${param} : ${param}
```

I assume that in the second line something existing is overwritten by itself. Therefore this line should not have any impact.

That's the case. The result is like expected:

`{'param': 'value'}`

Trying the same with a dictionary and a list:

```
"param" : {"A" : 1},
${param} : ${param}
```

```
"param" : ["A" , 1],
${param} : ${param}
```

Result in both cases:

`Error: 'expected string or bytes-like object'!`

But why is that? I would expect the same behavior like in the first example: After second line the `param` has same value as set in the first line.

**Comment by HolQue** [comment]
The code above work like expected now. But only for top level parameters. In TestsuitesManagement style it still does not work:

```
"params" : {"global" : {"param"  : ["A" , 1],
                        ${params.global.param} : ${params.global.param}
                       }
           }
```

Outcome:

`'The variable '${params}['global']['param']' is not available!'`

See also:

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/253

**Comment by HolQue** [comment]
Removed "successfully tested" label because of https://github.com/test-fullautomation/python-jsonpreprocessor/issues/213#issuecomment-1994356229

**Comment by HolQue** [comment]
Covered by self test JPP_1800

**Comment by namsonx** [comment]
Hello Holger,

I pushed new commit to stabi branch to fix this issue, I also enabled test case JPP_1800.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
