### ISSUE TITLE
"by reference" vs. "by value"

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#214]
In addition to

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/210

I extend the code by a third line in which I recreate `testdict2` (instead of `testdict1`):

```
${testdict1.subKey1.subKey2} : 1,
"testdict2" : ${testdict1},
${testdict2.subKey1.subKey2} : 2
```

The result is:

```
{'testdict1': {'subKey1': {'subKey2': 2}},
 'testdict2': {'subKey1': {'subKey2': 2}}}
```

The question is: How shall this assignment work:

`"testdict2" : ${testdict1},`

"_by reference_" or "_by value_"?

In pure Python it would be: "_by reference_". But the JsonPreprocessor code contains a lot of `copy.deepcopy()` calls. And this is an indicator for "_by value_".

Because of this makes a difference and because of it is necessary to explain this in documentation and to be able to design self test cases I would prefer to have this clarified: What is the desired value passing method in JsonPreprocessor: "_by reference_" or "_by value_"?

If "_by reference_", the result above is correct. The changed value of `subKey2` is visible in both `testdict1` and `testdict2`.
But if "_by value_", the result above is not correct. The expectation in this case would be to have two different objects that are independent from each other:

```
{'testdict1': {'subKey1': {'subKey2': 1}},
 'testdict2': {'subKey1': {'subKey2': 2}}}
```

**Comment by test-fullautomation** [comment]
Hi Son,
behaviour should be same like python does.
So "by reference" would be required.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas, Hello Holger,

If we refer "by reference" like Python dose, so there is nothing to do with current behavior of JP as Holger mentioned in ticket.

I use many ```copy.deepcopy``` to handle other stuffs such as checking ```dict``` or ```list``` in ```for``` or ```while``` loop, I always delete temporary objects from ```copy.deepcopy``` once checking completed.

Thank you,
Son

**Comment by HolQue** [comment]
Again I extended the code example from above (by a fourth line). Unfortunately this causes an error.

The following JSON code

* defines `testdict1` with some subkeys implicitly,
* assign this dictionary to another one (`testdict2`),
* change a key value using `testdict1` and also `testdict2`

```
${testdict1.subKey1.subKey2} : 1,
"testdict2" : ${testdict1},
${testdict2.subKey1.subKey2} : 2,
${testdict1.subKey1.subKey2} : 3
```

Result:

```
{'testdict1': {'subKey1': {'subKey2': 2}},
 'testdict2': {'subKey1': {'subKey2': 2}}}
```

But I would expect value **3** in both cases (instead of `2`).

**Comment by HolQue** [comment]
No problems with lists:

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/252#issuecomment-1992037429

**Comment by HolQue** [comment]
Covered by JPP_1900

**Comment by namsonx** [comment]
Hello Holger,

I fixed and uncovered test case ID JPP_1900, the commit was pushed into stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
