### ISSUE TITLE
Code clarification wanted

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#217]
The constructor of class `CJsonPreprocessor` gets an optional parameter "`currentCfg`". The interface description tells: "`Internally used to aggregate imported json files.`"

What exactly is the meaning of this parameter? What is the use case? I have not found any example.

Why is this parameter an input parameter for the constructor? Constructor parameter are the interface to the users of this class.
But the parameter is described as "`Internally used`". What have users to do with this parameter when this is an internal thing?

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your review comment! My description of the parameter in this case was not updated and it confuses you.

The use case of this parameter is:
    There is a configuration object existing in a Python program with name ```configData```, for example.
    Now, users want to load more configuration parameters from ```.jsonp``` file to this ```configData``` object, then they can initialize ```CJsonPreprocessor``` with an optional parameter ```currentCfg``` in the constructor.

I will update the description of this ```currentCfg``` parameter.

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.1 [06.09.24](jsonpreprocessor / tsm)**

**Comment by HolQue** [comment]
Hi Son,

oh, this is really a tricky feature. I gave it a try:

```
currentCfg = {"A" : 1, "B" : 2}
jsonpStr   = "{\"A\" : 11, \"C\" : 3}"
json_preprocessor = CJsonPreprocessor(currentCfg=currentCfg)
retValues = json_preprocessor.jsonLoads(jsonpStr)
pprint.pprint(retValues)
```

Outcome:

`DotDict({'A': 11, 'C': 3})`

`'B'` is missing.

I would expect:

`DotDict({'A': 11, 'B': 2, 'C': 3})`

**Comment by namsonx** [comment]
Hello Holger,

I created [the commit 25153aef3a3](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/25153aef3a3011660ed3ef2ffc0488cdd5a9689a) to fix the issue related to current config update feature.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
