### ISSUE TITLE
Execution interdependencies

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#222]
JSON code executed

```
{
   ${testdict1.subKey1.subKey2.subKey3} : {"subKey4" : 1}
}
```

results in valid values:

`{'testdict1': {'subKey1': {'subKey2': {'subKey3': {'subKey4': 1}}}}}`

Same code (same JSON file) executed again (within same Python process) results in an empty dictionary:

`{}`

This is if I use the same JsonPreprocessor object for both executions and also if I create a new object before each execution.

But the result should be the same in all cases.

**Comment by namsonx** [comment]
Hello Holger,

This issue was solved on stabi branch.

Thank you, 
Son

**Comment by namsonx** [comment]
Hello Holger,

This issue was solved on stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
