### ISSUE TITLE
Dictionary key not updated

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#223]
Topic: Implicitly create a dictionary. Overwrite value of subkey with different kind of syntax.

**A) Created in standard syntax; overwritten in ascending dotdict syntax:**

```
${testdict1} : {"subKey1" : {"subKey2" : {"subKey3" : {"subKey4" : 0}}}},
${testdict1.subKey1} : {"subKey2" : {"subKey3" : {"subKey4" : 1}}},
${testdict1.subKey1.subKey2} : {"subKey3" : {"subKey4" : 2}},
${testdict1.subKey1.subKey2.subKey3} : {"subKey4" : 3},
${testdict1.subKey1.subKey2.subKey3.subKey4} : 4
```

Outcome: `subKey4` has value `4` (like expected)

**B) Created in dotdict syntax; overwritten in ascending standard syntax:**

```
${testdict2.subKey1.subKey2.subKey3.subKey4} : 5,
${testdict2.subKey1.subKey2.subKey3} : {"subKey4" : 6},
${testdict2.subKey1.subKey2} : {"subKey3" : {"subKey4" : 7}},
${testdict2.subKey1} : {"subKey2" : {"subKey3" : {"subKey4" : 8}}},
${testdict2} : {"subKey1" : {"subKey2" : {"subKey3" : {"subKey4" : 9}}}}
```

Outcome: `subKey4` has value `8`! This is astonishing. Expected is  value `9`. Why is the last assignment ignored?

**C) Cross check:**

```
${testdict3} : {"subKey1" : {"subKey2" : {"subKey3" : {"subKey4" : 10}}}},
"testdict4" : {"subKey1" : {"subKey2" : {"subKey3" : {"subKey4" : 20}}}}
```

Outcome:

`subKey4` of `testdict3` has value `10` (like expected)
`subKey4` of `testdict4` has value `20` (like expected)

Seems that `${testdict}` and `"testdict"` is equivalent.

If this is like specified, the last line in example **B)** should also work.

**Comment by namsonx** [comment]
Hello Holger,

This ticket is fixed on stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
