### ISSUE TITLE
JsonPreprocessor freezes

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#226]
Hi Son,

with latest bugfix

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/195#issuecomment-1975020184

the JsonPreprocessor freezes with this JSON code:

```
"keyP"     : "A",
"B"        : 1,
"dictP"    : {"A" : "B", "C" : 2},
"newparam" : "${dictP['${keyP}']}"
```

Expected: `newparam` has value `'1'`

**Comment by namsonx** [comment]
Hello Holger,

I don't think the expected result of parameter ```newparam``` is ```'1'```, as current JP behavior, the value ```"${dictP['${keyP}']}"``` will convert ```${dictP['${keyP}']}``` to string.
In this case, it will convert ```"B"``` to string, and the result is still ```"B"```

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

you're right.

And now it seem to me that the syntax in my example is invalid (because of the square brackets inside the curly brackets).

This should be the valid syntax version:

`"newparam" : "${dictP}['${keyP}']"`

Now `newparam` is `'B'`.


Impact: The expected outcome of` "newparam" : "${dictP['${keyP}']}"` now would be an error message about an invalid syntax.

**Comment by HolQue** [comment]
And with this version

`"newparam" : "${${dictP}['${keyP}']}"`

`newparam` has string value `'1'`

:-)

**Comment by namsonx** [comment]
Hello Holger,

With this version ```"newparam" : "${${dictP}['${keyP}']}"```, the value will be converted to ```"${B}"```.
And ```${B}``` equal ```1```, so it will convert ```"${B}"``` to string ```'1'``` :)

I will fix the issue you mentioned above.

Thank you,
Son

**Comment by HolQue** [comment]
Another possibility to freeze the JsonPreprocessor (with valid syntax now):

```
"keyP"       : "A",
"B"          : "keyP",
"dictP"      : {"A" : "B"},
//
"newparam_1" : "${dictP}['${keyP}']",                  // => "${dictP}['A']" -> 'B'
"newparam_2" : "${${dictP}['${keyP}']}",               // => "${B}"          -> 'keyP'
"newparam_3" : "${${${dictP}['${keyP}']}}",            // => "${keyP}"       -> 'A'
"newparam_4" : "${dictP}['${${${dictP}['${keyP}']}}']" // => "${dictP}['A']" -> !!! freeze !!!
```

**Comment by namsonx** [comment]
Hello Holger,

Regarding to your first comment with jsonp file:
```
"keyP"     : "A",
"B"        : 1,
"dictP"    : {"A" : "B", "C" : 2},
"newparam" : "${dictP['${keyP}']}"
```
The value ```"${dictP['${keyP}']}"``` is invalid format instead return string ```"B"```, it should be ```"${dictP}['${keyP}']"``` as we defined before :)

I just want to correct the point above!

Thank you,
Son
I just want to ci

**Comment by HolQue** [comment]
Hi Son,

this is what I told in

https://github.com/test-fullautomation/python-jsonpreprocessor/issues/226#issuecomment-1976506063

**Comment by namsonx** [comment]
Hello Holger,

This ticket was solved on stabi branch!

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Holger,
the problem occurs again?
Thank you,
 Thomas

**Comment by HolQue** [comment]
The code samples used above, work now.

But the JsonPreprocessor still freezes.

Now with this (invalid) code:

```
   "listparam" : ["A","B","C"],
   "param" : "$}${listparam}[0]"
```

**Comment by HolQue** [comment]
Caution: The current _freeze_ effect has an impact on the self test of the TestuitesManagement. This test also freezes!

**Comment by namsonx** [comment]
Hello Holger,

I have just added mechanism to avoid Python run freezes to stabi branch.

For the issue related to invalid code ```"$}${listparam}[0]"```, I will check and fix.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

some details w.r.t. freezed TestsuitesManagement test:
https://github.com/test-fullautomation/python-jsonpreprocessor/issues/226#issuecomment-1983106596

Freezing is TSM_1200

Affected JSON file:

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/blob/develop/test/testfiles/config/tsm-test_config_composite_expressions_1.jsonp

**Comment by HolQue** [comment]
Issue w.r.t.

`"param" : "$}${listparam}[0]"`

is solved. Result is: `'$}A'`

TSM_1200 still freezes.

**Comment by namsonx** [comment]
Hello Holger,

I fixed the issue related to TSM_1200 freezes, could you please help me check!

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
