### ISSUE TITLE
Another list index out of range

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#227]
The code

```
"keyP"     : "A",
"B"        : 1,
"dictP"    : {"A" : "B", "C" : 2},
"newparam" : "${${dictP}['${keyP}']}"
```

results in `newparam` with string value `'1'` (like expected).

But when I omit the single quotes

`"newparam" : "${${dictP}[${keyP}]}"`

the result is:

`'list index out of range'!`

But expected is still `newparam` with string value `'1'` (because `keyP` is a string already, therefore the single quotes
do not have any effect)

**Comment by namsonx** [comment]
Hello Holger,

This issue is fixed on stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
