### ISSUE TITLE
terms and choice of words

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#239]
It seems to me that it's time to clarify and define the usage of some terms. Also to ensure that we all use these terms in an unitary way - in documentation, code and issues, and also in discussions with customers.

This is my proposal:

A '**dollar operator expression**' consists of a dollar operator and a pair of curly brackets: `${param}`.

In case of a dollar operator expression contains one or more than one dollar operator expression, it's a '**nested dollar operator expression**': `${param.${param}}`.

A subsequence of dollar operator expressions is not '**nested**' in my opinion: `${param}[${param}]`, `"ABC-${param1}_${param2}"`.

The first one '`${param}[${param}]`' I would simply call a '**dollar operator expression**'.

And the second one '`"ABC-${param1}_${param2}"`' I would call a '**composite string**'.

_Do you agree? Any additions?_

**Comment by test-fullautomation** [comment]
Hi Holger,
I would call `${param}[${param}]` also "nested".
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

finally this would be OK for me. But nevertheless: Are you really sure? It's not the dollar operator itself, that is nested. Affected are other parts of the syntax.

But is an index really something _nested_?

**Comment by test-fullautomation** [comment]
hm...
It's a bit difficult for me.
I would call it "nested" because you have recursively to resolve all $-expressions. No matter if it is sub-part of a $-expression, or like here part of an index.

**Comment by test-fullautomation** [comment]
Hi Holger,
After some thinking I come to following conclusion:
I would use the word "nested" if we have a dollar operator expression where we have inside at least one new dollar operator expression before the curly bracket of the first expression is closed.
E.g. from your example: `${param.${param}}`.

All other cases are sequences of $-expressions.

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
please remove in general the word "nested" from your error messages.
This has nearly no value for the end user, but makes it difficult for you to identify which exact error message you need to generate.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas, 

I removed the word "nested" out of all error messages on stabi branch.

Thank you,
Son

**Comment by test-fullautomation** [comment]
very good! I hopes it make generating error messages easier.

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
