### ISSUE TITLE
JsonPreprocessor need to return a dotdict 

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/python-jsonpreprocessor#246]
JsonPreprocessor need to return a dotdict (always be aware that a user can use python-jsonpreprocessor without testsuitesmanagement).
Only problem is that dotdict of JsonPreprocessor is other than the one used by Robot Framework.
Therefore testsuites-management need to do a conversion to Robot Framework's dotdict.
Thank you,
 Thomas

_Originally posted by @test-fullautomation in https://github.com/test-fullautomation/python-jsonpreprocessor/issues/245#issuecomment-2007146076_

**Comment by namsonx** [comment]
Hello Thomas,

This enhancement is available on stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
Released with RobotFramework AIO 0.12.0
