### ISSUE TITLE
Outdated old version of documentation

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#25]
The repository still contains the predecessor of "packagedoc": the "doc" folder - with the in between outdated Sphinx based documentation.

When the content is ported to the new folder completely, this "doc" folder should be removed.

**Comment by test-fullautomation** [comment]
Hi Son,
please correct this.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I created the pull-request #37  for this issue.

Thank you,
Son

**Comment by test-fullautomation** [comment]
already merged with #37
