### ISSUE TITLE
invalid group reference

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#251]
The code

`"param\\1"   : "value"`

causes:

`Error: 'invalid group reference 1 at position 12'!`

Seems that the parameter name is interpreted as regular expression directly.

Please check for unwanted side effects.

Finally this should cause an "invalid parameter name" error.

**Comment by HolQue** [comment]
Retest successful.

Error message now is: `Error: 'Invalid key name detected: '"param\\1"'.`

Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
