### ISSUE TITLE
Expression with not existing parameter not resolved

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#252]
In following three code examples the not existing parameter is detected properly:

```
"listP"  : ["A", "B"],
"params" : ${listP}[${IAMNOTEXISTING}]
```

```
"listP"  : ["A", "B"],
"params" : [${listP}[${IAMNOTEXISTING}], "ABC"]
```

```
"listP"  : ["A", "B"],
"params" : {"ABC" : [${listP}[${IAMNOTEXISTING}], "DEF"]}
```

Result:

`Error: 'The variable '${IAMNOTEXISTING}' is not available!'!`

But after adding another level of nested brackets:

```
"listP"  : ["A", "B"],
"params" : [{"ABC" : [${listP}[${IAMNOTEXISTING}], "DEF"]}, "GHI"]
```

the result is:

```
{'listP': ['A', 'B'],
 'params': [{'ABC': ['${listP}[${IAMNOTEXISTING}]', 'DEF']}, 'GHI']}
```

It is not detected any more that a parameter does not exist, and the entire dollar operator expression `${listP}[${IAMNOTEXISTING}]` is inserted as string into the list.

But expected is the same error message than above.

**Comment by namsonx** [comment]
Hello Holger,

This issue is fixed on statbi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

huge improvement!

Thank you.

Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
