### ISSUE TITLE
Parser harmed by line breaks

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#259]
This works:

```
"dictParam1" : {"kA" : "A", "kB" : "B"},
"dictParam2" : {"kA" : "A",
                "kB" : "B"},
"A" : 1,
"dictParam3" : {"kA" : "${A}", "kB" : "B"},
"dictParam4" : {"kA" : "${A}",
                "kB" : "B"},
"dictParam5" : {"kA" : ${A},
                "kB" : "B"}
```

The last one without line break in between does not work:

`"dictParam6" : {"kA" : ${A}, "kB" : "B"}`

`Error: 'Invalid parameter format: ${A}, "kB" - The double quotes are missing!!!'!`

Astonishing that '`, "kB"`' is part of the error message. Seems that the key-value-pair separation does not work properly.

But line breaks should not make a difference.

**Comment by HolQue** [comment]
Covered by JPP_1700

**Comment by namsonx** [comment]
Hello Holger,

I pushed the commit [aa5e0670f40](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/238/commits/aa5e0670f4028a146accea33ce324a0abec7200c) to fix the issue mentioned in this ticket.
I also updated expected result and enabled test case JPP_1700.
Please help me review and verify this issue.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
