### ISSUE TITLE
code examples

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#26]
Please align and harmonize the indentation of code in the code listings - especially the indentation of the opening and corresponding closing curly brackets. In current layout the listings are really hard to capture.

**Comment by test-fullautomation** [comment]
Hi Son,
I assigned this to me. I will look through the whole documentation and do a maintenance.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Holger,
please take this over.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Done with
https://github.com/test-fullautomation/python-jsonpreprocessor/pull/90
