### ISSUE TITLE
Error messages (12)

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/python-jsonpreprocessor#263]
the wording needs to be adapted:

Not: `Reason: Empty or special character is detected in pair of square brackets.`
But: `Reason: A pair of square brackets is empty or contains not allowed characters.`

Not: `Slicing is currently not supported!`
But: `Slicing is not supported!`

(no need to mention '_currently_', because then customers will assume that slicing might be available in near future already)

Not: `'Invalid expression while handling the parameter '${listP.${keyP}}'.'`
But: `'Invalid expression found: '${listP.${keyP}}'.'`

But nevertheless: This expression itself is not really invalid. It's a data type issue: List indices are expected to be positive integers, and not strings. Later this should be reworked.

_Originally posted by @HolQue in https://github.com/test-fullautomation/python-jsonpreprocessor/issues/238#issuecomment-2014728173_

**Comment by namsonx** [comment]
Hello Holger,

Thank you for you review! I made the change for this issue and the change was also merged to develop branch.

Thank you,
Son

**Comment by test-fullautomation** [comment]
released with RobotFramework AIO 0.13.0
