### ISSUE TITLE
Error messages (13)

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/python-jsonpreprocessor#264]
please remove the part "_Please update the expression_" from following error message:

`'Slicing is not supported! Please update the expression '${testlist}[1:]'.'`

In case of an error, it is obvious that the user has to do something to avoid this error. There is no need to mention this explicitly. Otherwise you would have to add such a statement to every error message.

Let's keep it short:

`'Slicing is not supported (expression: '${testlist}[1:]').'`

_Originally posted by @HolQue in https://github.com/test-fullautomation/python-jsonpreprocessor/issues/238#issuecomment-2019958905_

**Comment by namsonx** [comment]
The change is pushed to stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
released with RobotFramework AIO 0.13.0
