### ISSUE TITLE
JsonPreprocessor harmed by comnposite strings

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#265]
This works:

```
"index"     : 0,
"listParam" : [0,1,2],
"value"     : "A",
"dictParam" : {"A" : 1, "B" : 2},
"param1" : {"kA" : ${listParam}[${index}],
            "kB" : "${dictParam}[${value}]"}
```

`kB` has string value `'1'`

I add '`-X`' to the string value of `kB`:

```
"param1" : {"kA" : ${listParam}[${index}],
            "kB" : "${dictParam}[${value}]-X"}
```

Result:

`Expecting ',' delimiter: line ...`

But expected:

`kB` has string value `'1-X'`

**Comment by namsonx** [comment]
Ready for **sprint 0.13.1 [06.09.24](jsonpreprocessor / tsm)**

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
