### ISSUE TITLE
Index applied to a string does not work in dot notation

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#268]
In
https://github.com/test-fullautomation/python-jsonpreprocessor/issues/104
I asked if it shall be supported by the JsonPreprocessor to apply an index to a string.

Test case 
https://github.com/test-fullautomation/python-jsonpreprocessor/blob/develop/test/testfiles/jpp-test_config_1500.jsonp
gives evidence that this works fine. Therefore string indices should be handled as officially supported feature.

But this combination does not work:

```
"intParam" : 1,
"strParam" : "ABC",
"element"  : ${strParam.${intParam}}
```

Result:

`Error: 'Invalid expression found: '${strParam.${intParam}}'.'!`

For comparison, the same expression wrapped in quotes, work:

`"element" : "${strParam.${intParam}}"`

Result:

`{'element': 'B', 'intParam': 1, 'strParam': 'ABC'}`

(like expected)

The first code example should work also.

**Comment by HolQue** [comment]
Covered by JPP_1501

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
