### ISSUE TITLE
preprocessor definitions

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#27]
Some code listings contain preprocessor definitions. This feature does not exist currently. It is already decided not to mention preprocessor definitions any more. Please remove them.

**Comment by test-fullautomation** [comment]
Hi Holger,
the jsonpreprocessor doesn't know any semantics.
So, preprocessor has no meaning here and is therefore in general O.K.

But: It would be better to have fully generic code samples without any relationship to RobotFramework AIO. I will look into this (hopefully I find time).

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Son,
I assigned this to me. I will look through the whole documentation and do a maintenance.
Thank you,
Thomas

**Comment by test-fullautomation** [comment]
Hi Holger,
please take this over.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Done with
https://github.com/test-fullautomation/python-jsonpreprocessor/pull/90
