### ISSUE TITLE
redundant parts of documentation

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#28]
GenPackageDoc already adds the name of functions, classes and methods to the documentation. Therefore there is no need to do manually the same again within the docstrings of the Python modules.

For example: "Class: PythonJSONDecoder"

In the PDF document this name is written twice. Please remove all redundant docstring contents.

**Comment by namsonx** [comment]
Hello Holger,

I created the pull-request #38 for this issue.

Thank you,
Son

**Comment by test-fullautomation** [comment]
merged with #38
