### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#282]
In the past the time needed for the computation of some test code snippets, was approximately 1 second and lesser.

With https://github.com/test-fullautomation/python-jsonpreprocessor/pull/280 the computation time of some code snippets increased up to 4 seconds, in some cases to 8 - 16 seconds.

**Examples (time increased to ~ 4 sec, scope: params.global)**

```
"teststring/1"  : "teststring/1 value",
${params.global.teststring/1} : "${params.global.teststring/1} extended"
```

```
"list_param" : ["A", "B", "C"],
"val2"       : "${params.global.list_param[1]}"
```

```
"dict_param" : {"A" : 1 , "B" : 2},
"list_param" : ["A", "B", "C"],
"val3"       : "${params.global.list_param[${params.global.dict_param}['A']]}"
```

```
"dict_param" : {"A" : 1 , "B" : 2},
"list_param" : ["A", "B", "C"],
"val4"       : "${params.global.list_param[${params.global.dict_param}[${params.global.list_param}[0]]]}"
```

```
"dict_param" : {"A" : 1 , "B" : 2},
"list_param" : ["A", "B", "C"],
"val5"       : "${params.global.list_param[${params.global.dict_param}['${params.global.list_param}[0]']]}"
```

**Example (time increased to ~ 8 - 16 sec, scope: params.global)**

```
"teststring*1"  : "teststring*1 value",
${params.global.teststring*1} : "${params.global.teststring*1} extended"
```

This should be investigated.

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
please fix this urgently. 
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger,

Thank you very much for your findings! This issue occurred due to my mistake; I forgot to update a pattern back while trying to improve my code.
I pushed the tiny change ([commit ba1003b3922](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/ba1003b3922552dc57b92aadb7059f2e4aa07564)) to make the time needed for the computation less than 1 seconds.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
