### ISSUE TITLE
Incomplete error message

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#288]
In most of the cases, error messages contain a reason for the format being invalid, e.g.:

`errorMsg = f"Invalid parameter format: {sInput} - The double quotes are missing!!!"`

But the code contains also this:

```
if sInput.count("{") != sInput.count("}") or sInput.count("[") != sInput.count("]"):
    errorMsg = f"Invalid parameter format: {sInput.strip()}"
```

I would say, also here the reason (bracket mismatch) should be printed out, because the reason is known.

Is there a certain reason to count `if sInput.count("{")` instead of `if sInput.count("${")` like at other positions?

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding!
```Is there a certain reason to count if sInput.count("{") instead of if sInput.count("${") like at other positions?```
    -> This is my mistake, there is no certain reason for it. I fixed it.

I pushed the change to stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

two times in JsonPreprocessor code this is checked:

`sInput.count("${") > sInput.count("}"):`

But the impact is different:

```
errorMsg = f"Invalid syntax! One or more than one opened or closed curly bracket is missing in expression '{sInput.strip()}'."
errorMsg = f"Invalid parameter format: {sInput.strip()} - Closed curly bracket is missing."
```

Both messages have issues. Please correct and align.

Expected: `Invalid syntax! One or more than one closed curly bracket is missing in expression ...`

**Comment by namsonx** [comment]
> Hi Son,
> 
> two times in JsonPreprocessor code this is checked:
> 
> `sInput.count("${") > sInput.count("}"):`
> 
> But the impact is different:
> 
> ```
> errorMsg = f"Invalid syntax! One or more than one opened or closed curly bracket is missing in expression '{sInput.strip()}'."
> errorMsg = f"Invalid parameter format: {sInput.strip()} - Closed curly bracket is missing."
> ```
> 
> Both messages have issues. Please correct and align.
> 
> Expected: `Invalid syntax! One or more than one closed curly bracket is missing in expression ...`

Hello Holger,

I optimized these two cases into one, and the error message in this case is ```Invalid syntax! One or more than one closed curly bracket is missing in expression ...```

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.0 [09.08.24](jsonpreprocessor / tsm)**
