### ISSUE TITLE
Line breaks and string conversions

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#290]
Hi Son,

please avoid such manual line breaks:
`
raise Exception(f"\n{str(error)} in line: '{line}'")`

Because the output is:

```
Error: '
No closing quotation in line: '   "param" : ${'}''!
```

But expected is:

`Error: 'No closing quotation in line: '   "param" : ${'}''!`

What is the reason for this type cast: `str(error)` ?

My understanding is that already `f"{...}"` does the job.

**Comment by namsonx** [comment]
Hello Holger,

```What is the reason for this type cast: str(error) ?``` 
An error exception which is returned from ```try: ... except:``` is ```JSONDecodeError``` object. To handle this error as string, I usually covert it to ```str```.
But in the case you mentioned in this ticket, converting error to str datatype is not necessary, I'll update it.

Thank you,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.1 [06.09.24](jsonpreprocessor / tsm)**

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
