### ISSUE TITLE
Dynamic key names not blocked completely

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#297]
Three ways of defining a dictionary:

**(1)**

```
"strval"  : "A",
"dictval" : {"${strval}_2" : 1}
```

Result:

`Error: 'A substitution in key names is not allowed! Please update the key name "${strval}_2"'!`

This option works like expected: The dynamic key name is blocked.

**(2)**

```
"strval" : "A",
${dictval}['${strval}_2'] : 2
```

Result:

`{'dictval': {'A_2': 2}, 'strval': 'A'}`

The dynamic key name is not blocked. But should be.

**(3)**

```
"strval" : "A",
${dictval.${strval}_2} : 2
```

Result:

`{'dictval': {'A_2': 2}, 'strval': 'A'}`

The dynamic key name is not blocked. But should be.

Reference:
https://github.com/test-fullautomation/python-jsonpreprocessor/issues/270

**Comment by namsonx** [comment]
Hello Holger,

Based on the requirement https://github.com/test-fullautomation/python-jsonpreprocessor/issues/270#issue-2225694970 , I understood that we just only block when ```${...}``` operator on left side of a colon is placed inside double quotes.
```
Expressions on left side which contain $-operators inside double quotes shall be generally blocked.
e.g.
"${param}" : 1
"prefix_${param}_suffix" : 1

Goal is to reduce stabilization and testing effort.
Later when all other features are stable we can create a task to provide this feature.

$-operator as part of a string as value shall be supported, if the data type is a simple data type.
```
So. it means we just block in case users want to convert a value of a parameter to string and make it become a new parameter in a configuration file.
Could you please check with Thomas on this?

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

like mentioned in https://github.com/test-fullautomation/python-jsonpreprocessor/issues/270#issuecomment-2100694997

_To use dynamic key names is allowed, but only in case of a key with the resulting name does exist already. Therefore this mechanism can be used to overwrite the value of existing keys, but cannot be used to create new keys._

The original wording of issue 270:

"_Expressions on left side which contain $-operators inside double quotes shall be generally blocked._"

is therefore outdated now. Not "_generally blocked_" any more. Blocked only under certain conditions (see above).

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your confirmation! I will update this requirement soon.

Thank you,
Son

**Comment by namsonx** [comment]
Hello Holger,

I pushed the change to stabi branch for this ticket.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in 0.12.1
