### ISSUE TITLE
Wrong error message w.r.t. dynamic key names

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#301]
With

https://github.com/test-fullautomation/python-jsonpreprocessor/pull/296

the behavior of the JsonPreprocessor changed:

The code

```
"indexP" : 0,
"keyP"   : "A",
"listP"  : ["A", "B"],
${indexP.${keyP}} : "newvalue"
```

causes:

`Error: 'Identified dynamic name of key '${indexP.${keyP}}' that does not exist. But new keys can only be created based on hard code names.'!`

Previously the error message was:

`'The implicit creation of data structures based on parameter is not supported. New parameter 'indexP['A']' could not be created by the expression '${indexP.${keyP}}''`

This old error message is wrong and this is handled in https://github.com/test-fullautomation/python-jsonpreprocessor/issues/267

But the new error message is also wrong. The affected expression is not encapsulated in quotes. Therefore we do not speak here about dynamic key names.

Expected is another error message:

`TypeError: 'int' object is not subscriptable`

**Comment by namsonx** [comment]
Hello Holger,

I pushed the change [fb3bd815ee3](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/fb3bd815ee33986febef9ade6e732a0f36b31169) for this ticket to stabi branch, the error message in this case now is:
```Exception: Could not set parameter '${indexP.${keyP}}' with value 'newvalue'! Reason: 'int' object is not subscriptable```
I also updated the reference logs of selftest based on this change.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
integrated in 0.12.1
