### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#312]
The code

`"params" : {"A" : []}`

causes

`Error: 'list index out of range'!`

That's wrong. There is no list index out of range. It should be possible, to initialize an empty list.

No such problems if the empty list is a list element:

`"params" : {"A" : ["B", []]}`

is resolved properly:

`DotDict({'params': DotDict({'A': ['B', []]})})`

**Comment by namsonx** [comment]
Ready for **sprint 0.13.1 [06.09.24](jsonpreprocessor / tsm)**

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
