### ISSUE TITLE
Invalid cyclic import detection

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#315]
A JSON string contains a file import. The imported file contains another import. This imported file also contains another import.

```
sJSON = """{
   "[import]" : "./imports/imported.jsonp",
   "A" : 1
}"""
```

The JSON string is handed over to '`jsonLoads`':

`dictValues = oJsonPreprocessor.jsonLoads(sJSON)`

This works like expected. I get all values.

I exchange the relative path to the imported file by the corresponding absolute path:

```
sJSON = """{
   "[import]" : "D:/SWDEV/Dev_Python_3/TestScript/imports/imported.jsonp",
   "A" : 1
}"""
```

Now the result is:
`
Exception: Cyclic imported json file 'D:/SWDEV/Dev_Python_3/TestScript/imports/imported.jsonp'!`

But expected is to get the defined values.

No such problem with '`jsonLoad`'.

**Comment by namsonx** [comment]
Hello Holger,

I fixed this issue and pushed to stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
