### ISSUE TITLE
documentation of stand-alone usage (with python) missing

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#32]
I have a question: We explain that the RobotFramework_Testsuites needs to be imported in robot tests in the following way:

Library    RobotFramework_Testsuites    WITH NAME    testsuites

We explain that the RobotFramework_Testsuites works together with the JsonPreprocessor. But I cannot find any hint about what to do to import the JsonPreprocessor also. And the reason most probably is that this is already done by the RobotFramework_Testsuites. And when the RobotFramework_Testsuites does all the necessary things with the JsonPreprocessor, then there is nothing else to do for the users. The JsonPreprocessor is hidden.

But the JsonPreprocessor is also a component available in PyPi separately. Therefore it must be possible to use the JsonPreprocessor without the RobotFramework_Testsuites. And the consequence is that the user needs to know how to enable the JsonPreprocessor in his own Python code. In the documentation I only find informations about how to install
and informations about the JSON files. But what is missing is a full pure Python code example that demonstrates how to use the JsonPreprocessor in own Python code.

**Comment by test-fullautomation** [comment]
Jsonpreprocessor should not be mentioned in RobotFramework_TestsuitesManagement documentation. I was already unhappy about this.
This is a dependency package for RobotFramework_TestsuitesManagement which is provided pypi and transparently used by the user of RobotFramework_TestsuitesManagement.

When this answer is enough for you, then please close the issue.

**Comment by HolQue** [comment]
Hi Thomas,

OK, I will remove the mentioned "JsonPreprocessor" from test suites tutorial.

But what is still open is the second part of my question.

**Comment by test-fullautomation** [comment]
Hi Son,
what is the status here?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas and Holger,

The python-jsonpreprocessor has to become the dependency package of robotframework-testsuitesmanagement package, because the code of our testsuitesmanagement imports JsonPreprocessor. So, installing testsuitesmanagement process has to manage python-jsonpreprocessor as the dependency.

Only python-jsonpreprocessor itself can work stand-alone.

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,
here are some misunderstandings...

What is missing is a documentation for json-preprocessor which explains how to use it with python with corresponding python code samples in addition to the already existing json samples.

Please extend this for version 0.8.0.

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Holger,
please take this over.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Done with
https://github.com/test-fullautomation/python-jsonpreprocessor/pull/90
