### ISSUE TITLE
Absolute paths in samples

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#34]
The examples in

`python-jsonpreprocessor\sample`

contain an absolute Windows specific path:

`sys.path.append('D:\B\python-jsonpreprocessor')`

I suggest to implement in a more universal way:

`sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "./json")))`

**Comment by test-fullautomation** [comment]
Hi Holger,
you are right of course. I pushed a very early intermediate state...
I'll change this.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Son,
what is the status here?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas and Holger,

I created the pull-request #42 to resolve this issue.

Thank you,
Son

**Comment by test-fullautomation** [comment]
already merged #42
