### ISSUE TITLE
Naming convention check failed

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#343]
**OK:**

JSON: `"param" : {"key" : "${\}"}`
Result: `'Invalid key name: ${\}. Key names have to start with a character, digit or underscore.'`

**Not OK:**

JSON: `"param" : {"key" : "${/}"}`
Result: `'The parameter '${/}' is not available!'`

Also others like: `'The parameter '${$}' is not available!'`

But expected: `'Invalid key name: ${/}. Key names have to start with a character, digit or underscore.'`

I am not completely sure, but I would prefer the term 'letter' instead of 'character'. Because in my opinion also '/' and '\\' are characters (but not letters).

Recommendation:

`'Invalid key name: .... Key names have to start with a letter, digit or underscore.'`

**Comment by namsonx** [comment]
Hello Holger,

I pushed the change to stabi branch to fix this issue.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
merged for version 0.13.1
