### ISSUE TITLE
Naming convention violation (2)

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#354]
The naming convention tells: Key names have to start with a letter, digit or underscore.

But nevertheless the following JSON code throws an error:

`"𠼭param" : "value"`

Result:

`'Invalid key name: "ð ¼­param". Key names have to start with a letter, digit or underscore.'`

I move the special character to the right:

`"p𠼭aram" : "value"`

Now things are fine:

`[DOTDICT] (1/1) > {p𠼭aram} [STR]  :  'value'`

Seems that the check of the first character in key names has an issue. Because in general such special characters are accepted inside key names.

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
merged for version 0.13.1
