### ISSUE TITLE
Missing parameter in dynamic import

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#370]
JSON

`"[import]" : "./${I_AM_NOT_EXISTING}/imported.jsonp"`

causes

`Invalid expression found: '... /${I_AM_NOT_EXISTING}/imported.jsonp'.`

But expected:

`The parameter '${I_AM_NOT_EXISTING}' is not available!`

**Comment by HolQue** [comment]
JPP_1154

**Comment by HolQue** [comment]
Result changed to

`'maximum recursion depth exceeded while calling a Python object'`

**Comment by namsonx** [comment]
Hello Holger,

This ticket was solved in stabi branch. Could you please help me verify again.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
merged for version 0.13.1
