### ISSUE TITLE
Subsequent dynamic imports not working

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#374]
JSONP:

```
"imports_dir" : "imports",
"[import]"    : "./${imports_dir}/global_defs.jsonp",
"[import]"    : "./${imports_dir}/${dictDirs.AA}/${listDirs.1}/imported.BB.jsonp"
```

The first imported file (**global_defs.jsonp**) contains information about `dictDirs` and `listDirs` that are used to import the second file.

Result:

`Invalid expression found: '... /${imports_dir}/${dictDirs.AA}/${listDirs.1}/imported.BB.jsonp'.`

Means: `dictDirs` and `listDirs` are not known. But should.

Cross check with first import fix instead of dynamic:

```
"imports_dir" : "imports",
"[import]"    : "./imports/global_defs.jsonp",
"[import]"    : "./${imports_dir}/${dictDirs.AA}/${listDirs.1}/imported.BB.jsonp"
```

Now it works:

```
{'BB': 2,
 'dictDirs': DotDict({'AA': 'AA', 'BB': 'BB', 'CC': 'CC'}),
 'imports_dir': 'imports',
 'listDirs': ['AA', 'BB', 'CC']}
```

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding! I pushed the change to stabi branch to fix this issue.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
