### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#387]
A cyclic import of JSON files causes a "_maximum recursion depth_" error in 2 variants:

* JSON file imports itself: "maximum recursion depth exceeded while calling a Python object" (**JPP_1152**)
* JSON file imports another file, that is already imported: "maximum recursion depth exceeded in \_\_instancecheck\_\_" (**JPP_1153**)

Both based on dynamic import paths.

Successor of https://github.com/test-fullautomation/python-jsonpreprocessor/issues/380 (imports are resolved now)

**Comment by namsonx** [comment]
Hello Holger,

This ticket was solved on stabi branch.

Thank you,
Son

**Comment by namsonx** [comment]
Hello Holger,

This ticket was implemented and pushed to stabi branch.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.

**Comment by test-fullautomation** [comment]
merged for version 0.13.1
