### ISSUE TITLE
Adaption of type prefix recommended

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#57]
Because of the data type has been changed from `list` to `dict`:

`self.lUpdatedParams = []` -> `self.lUpdatedParams = {}`

The type prefix should be adapted also: `self.dUpdatedParams`

**Comment by namsonx** [comment]
Hello Holger,

Thank you for the finding! I created new pull request #112 for the correction.

Thank you,
Son

**Comment by test-fullautomation** [comment]
solved and already merged with #112
