### ISSUE TITLE
atest folder update to new jsonp extension

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#63]
Might it makes sense to adapt the

`python-jsonpreprocessor\atest`

sources to the new extension `jsonp`?

**Comment by test-fullautomation** [comment]
Hi Holger,

jsonpreprocessor should be generic and not dependent on any file-ending.

hm...

Maybe we make one simple and one complex (with multiple imports) tests if all works as expected if we use jsonp as file ending.

Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

OK, but consider: Using the new extension `jsonp` also in test code would avoid invalid findings in VSCodium error.

Or we make it a certain hint in documentation.

* Possibility 1: Avoid every preprocessor specific syntax extensions when using extension `json` together with standard editors or standard JSON syntax checkers.
* Possibility 2: Switch to extension `jsonp` and use adapted language definitions like available as extension for VSCodium.

**Comment by test-fullautomation** [comment]
Hi Holger,

O.K. I agree w.r.t. VSCodium.
Actually jsonpreprocessor introduces the syntax, therefore tests should be written as jsonp files, too.

But important is that the jsonpreprocessor code has zero dependency on the extension name.

Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

I created the commit [1ad5fb86c](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/1ad5fb86cb1b8073c1458559dd9053739bddf2d8) on stabi branch for this ticket.

Thank you,
Son

**Comment by namsonx** [comment]
merged to develop branch
