### ISSUE TITLE
${...} substitution

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#76]
Reference: https://github.com/test-fullautomation/python-jsonpreprocessor/issues/69

I tried some use cases:

```
"str1" : "ABC",
"str2" : "DEF",
"str3" : ${str1},
"list" : ["A", "B", "C"],

// "str4" : ${str1}_test_${str2}
// -> Expecting ',' delimiter

// "str5" : "${str1}_test_${str2}"
// -> Expecting ',' delimiter

// ${str1}_test_${str2} : "MNO",
// -> Expecting property name enclosed in double quotes

// "${str2}_test_${str3}" : "SPQR"
// -> Expecting ':' delimiter

// "${str1}_test_${list}" : "XYZ"
// -> Expecting ':' delimiter
```

* `str1` - `list` are successful.
* `str4` and `str5` cause an error.

What shall be the desired implementation in case of multiple substitutions on the right hand side of the colon: expression encapsulated in quotes or not?

Same question in case of multiple substitutions on the left hand side of the colon: expression encapsulated in quotes or not?

Both causes errors.

The last example contains a composite data type `${list}` on the left hand side of the colon. As per
https://github.com/test-fullautomation/python-jsonpreprocessor/issues/69#issuecomment-1589581903
this should not be allowed. But the issue comment is related to the Testsuites Management. For me the question now is: Shall the JsonPreprocessor react in the same way or shall the JsonPreprocessor allow composite data types on the left hand side of the colon?

Nevertheless: The error message should not tell about a missing delimiter. This is not helpful.

**Comment by HolQue** [comment]
Addendum:

While playing around I overlooked something. `list` is a data type. It is not possible to use names of data types as parameter name. This does not work:

```
   "str"  : ${str1},
   "list" : ["A", "B", "C"]
```
Must be something different instead:

```
   "str1"  : ${str1},
   "list2" : ["A", "B", "C"]
```

I understand that the first version is not possible, but the error message is not nice:

```
Traceback (most recent call last):
  File "D:\ROBFW\Dev\JsonPreprocessorTest\JsonPreprocessorTest.py", line 27, in <module>
    dictValues = oJsonPreprocessor.jsonLoad(r"./config/test1.jsonp")
  File "D:\RobotFramework\python39\lib\site-packages\JsonPreprocessor\CJsonPreprocessor.py", line 740, in jsonLoad
    oJson, bNested = self.__updateAndReplaceNestedParam(oJson)
  File "D:\RobotFramework\python39\lib\site-packages\JsonPreprocessor\CJsonPreprocessor.py", line 520, in __updateAndReplaceNestedParam
    elif isinstance(v, list):
TypeError: isinstance() arg 2 must be a type or tuple of types
```

Maybe this can be improved.

Addendum:

It can be improved by:

```
import keyword
key_name = "import"
if key_name in keyword.kwlist:
   print(f"Invalid keyname '{key_name}' (name is reserved for Python)")
```

**Comment by HolQue** [comment]
Another use case: composite data type as part of expression on left hand side of colon; expression not encapsulated in quotes:

```
   "str2" : "DEF",
   "values" : ["A", "B", "C"],
   ${values}_test_${str2} : "XYZ"
```

Outcome: `values_test_DEF = 'XYZ'`

Now I am not sure about the expectation any more. Shall `${values}` be resolved or not? I do not believe that simply using the parameter name as string is really helpful.


Addendum 1:

Regarding `${values}_test_${str2} : "XYZ"` I learned in between: Because the key name is a mix of parameters and hard coded parts, the entire expression must be enclosed in quotes:

`"${values}_test_${str2}" : "XYZ"`

The version without quotes on the left hand side of the colon is therefore a syntax violation and should cause a corresponding error message.

Rule: If expression contains one or more `${...}` together with parts outside `${...}`, but is not encapsulated in quotes, then syntax violation error message.

The version with quotes must also not be accepted because `${values}` refers to a composite data type that is not allowed as part of a key name.

Addendum 2:

Same with (mentioned above):
```
// "str4" : ${str1}_test_${str2}
// -> Expecting ',' delimiter
```

This is a valid error! Because the value is a mix of parameters and hard coded parts, the entire expression must be enclosed in quotes. But the error message `Expecting ',' delimiter` makes no sense.

The same rule like mentioned above should be applied: If expression contains one or more `${...}` together with parts outside `${...}`, but is not encapsulated in quotes, then syntax violation error message.

**Comment by HolQue** [comment]
Regarding this error:

`Expecting ':' delimiter`

caused by lines e.g. like

`"ABC_${str3}_test_${str1}_XYZ" : "MNOT",`

In CJsonPreprocessor.py I added a print (`print(f"{sJsonDataUpdated}")`):

```
try:
    oJson = json.loads(sJsonDataUpdated,
                       cls=CJSONDecoder,
                       object_pairs_hook=self.__processImportFiles)
except Exception as error:
    print(f"{sJsonDataUpdated}")
```

Outcome:

`"ABC_"${str3}"_test_"${str1}"_XYZ" : "MNOT",`

Oh, this is not nice. Nested double quotes are not possible here. This does not work.

But I wonder why inside `sJsonDataUpdated` the parameters are not already resolved, and I also wonder why there are double quotes around "`${str3}`" and "`${str1}`"? It makes no sense to add them.

**Comment by test-fullautomation** [comment]
Hi Son,
please look into this.
Expectation is what Holger writes.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger,

The scenario: 
// "str5" : "${str1}_test_${str2}"
// -> Expecting ',' delimiter
This case is working fine now with pull-request #81 

Thank you,
Son

**Comment by HolQue** [comment]
Hello Son,

the situation is unclear to me. You have updated an already merged pull request? Is this a good idea?

Git tells me that I am already up to date. Therefore I downloaded the Python file directly from this web page. But I got a file that does not contain your recent changes (e.g. the reset function).

For me it makes no sense to continue in this way. You should create a fresh new branch, and as long we are in summer vacation phase you should upload all changes in this single branch only. Please no different versions located in different branches or pull requests in parallel. Otherwise no one will know what he can expect.

**Comment by namsonx** [comment]
Hello Holger,

I'm still implement the scenarios you mentioned in this tickets, when completed I will create new branch for testing purpose.

Regarding to the scenarios below:
// ${str1}_test_${str2} : "MNO",
// -> Expecting property name enclosed in double quotes

// "${str2}_test_${str3}" : "SPQR"
// -> Expecting ':' delimiter

// "${str1}_test_${list}" : "XYZ"
// -> Expecting ':' delimiter
A key dose not allow containing more than 2 nested parameters, because when a nested parameter is defined as a key, it means user want to overwrite new value for existing parameter.
For example:
I have Json config file like below:
```
{
    "nested_param" : 2017,
    "test_param" : "Just for testing",
    "var" : {
        "var_1": {
            "var_2" : {
                "var_3" : "initialized"
            }
        }
    },
    ${var}['var_1']['var_2']['var_3']: "new value",      
    "val08" : null
 }
```

The line ${var}['var_1']['var_2']['var_3']: "new value", will update the value of var['var_1']['var_2']['var_3'] to "new value" not set "initialized" : "new value". 

Thank you,
Son

Addendum:

Hi Son,

yes! And when you add quotes like:

`"${var}['var_1']['var_2']['var_3']" : "new value",`

then the JsonPreprocessor should provide:

`"initialized" : "new value"`

**Comment by namsonx** [comment]
Hello Holger,

I created new branch [namsonx/testing/testing_branch](https://github.com/test-fullautomation/python-jsonpreprocessor/tree/namsonx/testing/testing_branch) and merged all new changes to this new branch for testing purpose.
You can verify the scenarios by using this new branch.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

good idea! Thank you very much.

I executed this version and compared the log file of the self test with the log file of the previous execution. Lots of differences ;-)

Some issues are fixed. But it seems, that there are new issues also. Some aspects of the changed behaviour I do not understand and I need to take a deeper look at it. I will give feedback soon step by step.

**Comment by namsonx** [comment]
Hello Holger,

For the cases 
```
   "str"  : ${str1},
   "list" : ["A", "B", "C"]
```
We allow a key name to coincide with the name of built-in keywords in Python, because these key names is a part of Json object output, they are not Python variables.
I implemented method __checkParamName() to add temporary prefix to the key name which coincide with python keywords to handle nested parameters, this temporary prefix is removed when updating returned Json object.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

yes, I already detected that the previous error message does not occur any more.

In general it is OK for me. But some doubts are left.

Do we really want to have reserved Python keywords as key names? Really?
It is a good practice to choose names that are self-explanatory. Therefore, why should we allow the users to give a string variable the name `str`?

Can we be sure that such a name has no further unwanted side effects?

**Comment by namsonx** [comment]
Hello Holger, Hello Thomas,

As our discussion, we want allow ${...} substitution in parameter name but it will conflict in case user want to overwrite the exist parameter, for example:
we have jsonp file like below:
```
{
    "str1" : "ABC",
    "str2" : "DEF",
    ${str1} : ["A", "B", "C"]
}
```
The output after handling with jsonpreprocessor should be:
```
{
    "str1" : "ABC",
    "str2" : "DEF",
    "ABC" : ["A", "B", "C"]
}
```
or 
```
{
    "str1" : ["A", "B", "C"],
    "str2" : "DEF"
}
```

I would propose the solution below:

- In case a parameter name contains only "${...}" or "${...}[..][...]", jsonpreprocessor will overwrite the exist parameter with new value.

- In case a parameter name is mixed like "abc_${....}", jsonpreprocessor will do substitution in this case (we call it dynamic parameter name feature).

Please give me your comment on my proposal?

Thank you,
Son

**Comment by HolQue** [comment]
Substitution vs. overwriting

```
{
   "param1" : "ABC",
   "param2" : "XYZ",
   //
   ${param2} : ${param1},
   "${param2}" : ${param1}
}
```

**Overwriting:**

With `${param2} : ${param1}` the initial value `"XYZ"` of parameter `param2` is overwritten with the value `"ABC"` of parameter `param1`.

**Substitution:**

With `"${param2}" : ${param1}` a new parameter with name `XYZ` (the value of `param2`) and value `"ABC"` is created.

The quotes around `${param2}` make the difference.

**Comment by HolQue** [comment]
What about
`${param2}['sub1'][ 'sub2'] : "DEF"`

vs 
`"${param2}['sub1'][ 'sub2']" : "DEF"`

First one overwrites 'sub2'
Second one creates a new variable with name that is the value of sub2.

**Comment by test-fullautomation** [comment]
Hi Son,

here again a sample for overwriting vs. substitution (I made this sample together with Holger):


Overwriting (key without double quotes):
```
{
   "param1" : "ABC",
   "param2" : "XYZ",
   //
   ${param2} : ${param1},
}
```

results in:
```
{
   "param1" : "ABC",
   "param2" : "ABC",
}
```

AND with key in double quote we have substitution:

```
{
   "param1" : "ABC",
   "param2" : "XYZ",
   //
   "${param2}" : ${param1}
}
```

results in:

```
{
   "param1" : "ABC",
   "param2" : "XYZ",
   "XYZ" : "ABC",
}
```

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
w.r.t to python datatype names as key name:
This shall be allowed on JsonPreprocessor level.
If robotframework-testsuitesmanagement has problems with this, then we have to take care on testsuitesmanagement level.

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Retest successful.

Overwriting and substitution work properly. Python data types are accepted as parameter name.

Ticket can be closed.
