### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#77]
The following assignment within a JSON file causes a crash of the JsonPreprocessor:

`"value" : "ab${cde"`

Error message: `IndexError: list index out of range`

Reason:

File: **CJsonPreprocessor.py**, method: **__nestedParamHandler**

Shortened code:

```
referVars = re.findall('(\${\s*.*?\s*})', sInputStr)
if len(referVars) > 1:
    sUpdateVar =  referVars[0]
.....
else:
    if "." in referVars[0]:
.....
```

`referVars` can also be empty (`len(referVars) == 0`). Under `else` we cannot be sure that `referVars[0]` exists. This must be checked.

Proposal: 

In case of `len(referVars) == 0` together with `number of '{' != number of '}'`: error message telling about invalid `$`-syntax.

Example:

```
elif len(referVars) == 0:
    nNrOfOpened = sInputStr.count('${')
    nNrOfClosed = sInputStr.count('}')
    if nNrOfOpened != nNrOfClosed:
        raise Exception(f"Dollar syntax violation in line '{sInputStr}': opened elements: {nNrOfOpened}; closed elements: {nNrOfClosed}")
```

Outcome:

`Dollar syntax violation in line 'ab${cde': opened elements: 1; closed elements: 0`

**Comment by HolQue** [comment]
Next question:

How to handle the last closed curly bracket in

`"value1" : "ab${cde}}",`

?

There are several combinations possible where we have to define how to handle:

**My proposals:**

Should be allowed; string stays untouched:
* `"abcde}}"`
* `"ab{{{cde}"`
* `"$ab{cde}}"`

In case of '`${`' is inside, rules have to be more strict:

Should not be allowed (error message):

* `"${abcde}}"`
* `"${{abcde}"`
* `"${ab}{{cde}"`

The rule is: In case of '`${`' is inside, the number of opened and closed brackets must be the same.

In case of a user wants to have both a dollar expression and further single curly brackets, these additional brackets have to be masked:

Should be allowed:
* `"${abcde}\}"`
* `"${ab}\{\{cde\}"`

But this makes no sense (I would assume an error):
* `"${\{abcde}"`

This does not contain '`${`' immediately (I would assume that this is accepted and the string stays untouched)
* `"$\{{abcde}"`

**Comment by HolQue** [comment]
The current reaction on

`"value1" : "ab${cde}}",`

is

`Expecting ',' delimiter:`

This error message makes no sense for the users and should be improved.

**Comment by HolQue** [comment]
Possible solution:

We need a naming convention for key names. Key names have to be checked against some rules:

* key name must not be a reserved Python and also not a reserved Robot Framework keyword.
* key name is allowed to contain [A-Z][a-z][0-9]_- only (and dots - but everyone must be aware of that dots inside key names have impacts)

**Comment by test-fullautomation** [comment]
Hi Son,
please look into this.
Expectation is what Holger writes.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding!
Regarding to your proposal:
Should be allowed; string stays untouched:

- "abcde}}"

- "ab{{{cde}"

- "$ab{cde}}"

In case of '${' is inside, rules have to be more strict:

Should not be allowed (error message):

- "${abcde}}"

- "${{abcde}"

- "${ab}{{cde}"

In case we allow brackets inside a string as your first statement, then we raise an error message for this case "${abcde}}", "${ab}{{cde}"
Could you please review this proposal again?

Thank you,
Son

**Comment by namsonx** [comment]
Hello Holger,

I propose that in case of '${' inside a string, we also allow "${abcde}}" and "${ab}{{cde}".
We will check if the number of '${' is less than the number of '}', then we will raise an error message as you mentioned in previous comment.

Please let me know your opinion?

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son, Hi Thomas,

a string contains matching pairs of '${' and '}' and additional '{' and '}'.

The question is: How to handle these additional brackets?

- They can be handled as error, because it is not really obvious what belongs together (assuming also possible typing mistakes made by user).
- They can be accepted without error (assuming that the user wants to have them; but it must be obvious in this case: The '}' that belongs to '${', will be searched non greedy.

@Thomas,
Please decide what you would prefer.

**Comment by test-fullautomation** [comment]
Hi both,

hm... in general additional brackets are not an error. The value can be a fragment of a longer string and therefore it can contain any even or odd number of brackets.

Therefore:

1. once `${` is found we can search a parameter. If there is no parameter inside we need to raise an error that a closing curly bracket is missing. Counting brackets is not working. `{${abc}` or  `${abc}}`, ... must be allowed.
Could be e.g. `${abc def}` with an accidental space inside the parameter name?

2. Backslash can be used to escape `\$` then all is just a string.

3. `"${abcde}}"`   allowed
4. `"${{abcde}"`  allowed, but no parameter as per naming convention
5. `"${ab}{{cde}"`  allowed

Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

regarding second point: escaped `\$`: Also the curly brackets can be escaped. How to handle?

```
"param1" : "value"
"param2" : "${param1}"
"param3" : "\${param1}"
"param4" : "$\{param1}"
"param5" : "${param1}\}"
"param6" : "${param1\}"

```
This should cause:

```
param2 = "value"
param3 = param4 = "${param1}" (dollar operator not resolved!)
param5 = "value}"
```

Is my understanding right here?

How about `param6`? I would expect that consequently the masking of the closed curly bracket moves this bracket out of syntax (the bracket has no syntactical meaning any more). Therefore a closing curly bracket (that matches to `${`) is missing now. Outcome should be a syntax error.

**Comment by namsonx** [comment]
Hello Holger, Hello Thomas,

This enhancement is implemented on stabi branch ([namsonx/task/stabi_branch](https://github.com/test-fullautomation/python-jsonpreprocessor/tree/namsonx/task/stabi_branch))

Thank you,
Son

**Comment by HolQue** [comment]
The initial issue (error message: `IndexError: list index out of range`) is solved.

Now it's: `Invalid nested parameter format`. That's better.

The remaining discussions in this issue are hard to capture. What are the _definitions of done_?

I tried some of the discussed combinations:

```
"param1" : "value",
"param2" : "${param1}",
```

The following combinations cause a "Invalid escape" error:
```
"param3" : "\${param1}"
"param4" : "$\{param1}"
"param5" : "${param1}\}"
```
This combination causes a "Invalid nested parameter format" error:
`"param6" : "${param1\}"`

Proposal:
* We agree that escaping is currently not supported by the JsonPreprocessor
* I add a hint about that in documentation
* Improvement: Maybe it's possible to change the error message in last combination also to "Invalid escape". Would be more plausible
* We close the ticket

**Comment by test-fullautomation** [comment]
Hi Holger,
I propose to close the ticket.
For 0.10.0 we create a new ticket w.r.t escaping must be possible. Then we have to look into the error messages, too.
Regards, 
 Thomas
