### ISSUE TITLE
Python syntax in JSON files

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#84]
The JsonPreprocessor introduces some useful extensions of the JSON format. In my opinion they should be available all per default.

But the possibility to use the Python keywords `True`, `False `and `None` is only enabled with the extension `syntax="python"` when creating a class object:

`CJsonPreprocessor(syntax="python")`

In my opinion the syntax switch is not really useful for developers. When someone uses the JsonPreprocessor, he wants to have the features available. Why having the need to activate them explicitely?

The syntax switch should either be removed or set to `"python"` per default within the JsonPreprocessor code (to avoid that the users have to do this in their own code).

**Comment by test-fullautomation** [comment]
Hi Son,
this is confirmed from me. Please implement accordingly.
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger,
 
I set python syntax as default when initializing JsonPreprocessor via the pull-request #113 

Thank you,
Son
