### ISSUE TITLE
Error while accessing a list element

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#85]
I try to access the first element of a list parameter with:

`"element_1" : ${componentB_param_1}[0]`

This causes a

`Expecting ',' delimiter`

error.

With quotes around the expression at the right hand side of the colon, it works:

`"element_1" : "${componentB_param_1}[0]"`

But I would expect that the quotes are not required.

**Comment by namsonx** [comment]
Hello Holger, Hello Thomas,

This issue was fixed in the pull-request #96 which already merged to develop branch.

Thank you,
Son
