### ISSUE TITLE
Colon inside string harms parameter substitution

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#92]
This works:

`"test_parameter" : "ABC : DEF",`

But in case of a dollar operator expression is involved also:

`"test_parameter" : "ABC ${value} : DEF"`

I get the following error message:

`Expecting ',' delimiter`

But colons inside strings must not harm the JSON parser.

**Comment by HolQue** [comment]
Retest not successful.

Issue still needs to be fixed.

**Comment by test-fullautomation** [comment]
removed "fix in review" state.

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas, Hello Holger,

I made the new commit [aa18fff1](https://github.com/test-fullautomation/python-jsonpreprocessor/pull/151/commits/aa18fff1f10b4e9781af5c2eac1c74dd23aa4249) on stabi branch to fix the issue which is mentioned in this ticket.

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Ticket can be closed.
