### ISSUE TITLE
Dollar operator substitution for key names fails (2)

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#93]
Similar to https://github.com/test-fullautomation/python-jsonpreprocessor/issues/91

JSON file:

```
"string_01" : "ABC",
"string_02" : "DEF",
${string_01}_composite_param_name_${string_02} : "(1.01)--'${string_01}'--(1.02)--'${string_02}'"
```

The third parameter name is a composite string. Because of that it is expected that the entire expression is encapsulated in quotes:

`"${string_01}_composite_param_name_${string_02}"`

Because of the quotes are missing I expect a syntax error, but the JsonPreprocessor generates this name:

`string_01_composite_param_name_DEF`

with the first parameter not resolved properly.

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Son implements and waits for retest from Holger.

**Comment by namsonx** [comment]
Hello Holger, Hello Thomas,

For the jsonp file with content:
```
"string_01" : "ABC",
"string_02" : "DEF",
${string_01}_composite_param_name_${string_02} : "(1.01)--'${string_01}'--(1.02)--'${string_02}'"
```
The JsonPreprocessor will issue the error message:
```
Exception: Invalid nested parameter format: ${string_01}_composite_param_name_${string_02} - The double quotes are missing!!!
```
If we put this key name into the double quotes, the output will show as below:
```
string_01 : ABC
string_02 : DEF
ABC_composite_param_name_DEF : (1.01)--'ABC'--(1.02)--'DEF'
```
I had implemented it long time ago but forgot updating this ticket.

Could you please help me check?

Thank you,
Son

**Comment by HolQue** [comment]
Retest successful. Issue can be closed.
