### ISSUE TITLE
List of use cases

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#95]
Hi Son,

this issue is not an error to fix!

I am currently planning my next steps regarding documentation and self test development for the JsonPreprocessor. To get an overview about the amount of aspects to be considered, I created the following list of test cases. I plan to implement these test cases and to update the documentation within the next days.

Maybe this list is also helpful for you; while developing the new features planned for the JsonPreprocessor.

Please refer to 
https://github.com/test-fullautomation/python-jsonpreprocessor/blob/HolQue/task/selftest_and_documentation_extensions/test/testconfig/Checklist.txt

**Comment by HolQue** [comment]
Because of ongoing maintenance, the checklist is - from now on - available (and maintained!) here:

https://github.com/test-fullautomation/python-jsonpreprocessor/blob/HolQue/task/selftest_and_documentation_extensions/test/testconfig/Checklist.txt

Later - after integration - in develop branch also.

**Comment by test-fullautomation** [comment]
removed outdated information from initial description.

**Comment by HolQue** [comment]
With the checklist I have communicated what I wanted to communicate.

Ticket can be closed.
