### ISSUE TITLE
Memory interferences in case of subsequent method calls with same class object

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#98]
The following test code contains two method calls with the same class object:

```
json_preprocessor = CJsonPreprocessor(syntax="python")
try:
   values1 = json_preprocessor.jsonLoad("./jpp-test_config_0201.jsonp")
   pprint.pprint(values1)
   values2 = json_preprocessor.jsonLoad("./jpp-test_config_0900.jsonp")
   pprint.pprint(values2)
except Exception as reason:
   print(f"'{reason}'")
```

Commenting out the first call (`0201`) causes the second call (`0900`) to return the expected values.

But when I include the first call, then the values returned from the second call contain parts of the values belonging to the first call (parts only - not the entire 0201 jsonp content!).

Seems that the JsonPreprocessor keeps values in memory after execution of `jsonLoad`, but it would be better to have a strict separation. Maybe a _reset_ or a _delete_ is missing at end?

This effect does not occur in every jsonp file combination. Seems that the effect depends on the data structure of the previous call. The file jpp-test_config_0201.jsonp contains nested parameters.

All jsonp files can be found here:
https://github.com/test-fullautomation/python-jsonpreprocessor/tree/HolQue/task/selftest_and_documentation_extensions/test/testfiles

**Comment by HolQue** [comment]
Addendum:

With the latest adaptions in
https://github.com/test-fullautomation/python-jsonpreprocessor/tree/HolQue/task/selftest_and_documentation_extensions/test
some command line extensions are available. This allows to test in a more flexible way.

Semicolon separated list of tests possible. This will carry out `JPP_0201` and `JPP_0900` only:
`"%RobotPythonPath%/python.exe" "./component_test.py" --testid="JPP_0201;JPP_0900"`
This runs in a loop. The JsonPreprocessor class object is created (and deleted) outside the loop (default!).

Outcome: All tests work with the same class object.

With
`"%RobotPythonPath%/python.exe" "./component_test.py" --testid="JPP_0201;JPP_0900" --recreateinstance`
the JsonPreprocessor class object is created (and deleted) inside the loop.

Outcome: All tests work with their own class object.

You can analyze the issue described above by executing both command lines and comparing the results

In first case `JPP_0900` fails; in second case `JPP_0900` is successful.

**Comment by HolQue** [comment]
Addendum:

Hi Son,

I suggest to execute the entire test with

`"%RobotPythonPath%/python.exe" "./component_test.py"`

and with

`"%RobotPythonPath%/python.exe" "./component_test.py" --recreateinstance`

and compare the result in

`test/testlogfiles/JPP_SelfTest.log`

You will find lots of differences.


Addendum:

Test description:

https://github.com/test-fullautomation/python-jsonpreprocessor/blob/HolQue/task/selftest_and_documentation_extensions/test/readme.rst

**Comment by namsonx** [comment]
Hello Holger,

I will implement a reset method in CJsonPreprocessor object, so whenever user want to load new jsonp configuration file with existing CJsonPreprocessor instance, user can call <exist_instance>.reset() before calling <exist_instance>.jsonLoad()

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

why do you want to give the responsibility for such a reset to the user? What is the usecase behind the idea to keep results from previous method calls in current method call? We speak about a severe bug here! Calling such a reset function is not a users option.

Please execute this reset function implicitely at end of every jsonLoad().

**Comment by namsonx** [comment]
Hello Holger,

Because first user initialized 1 new instance json_preprocessor = CJsonPreprocessor(syntax="python") in your program, then user call method jsonLoad() to load json object, and in json_preprocessor instance I store the list of nested parameters, dotdict parameters.

In case we implement the reset function in the end of jsonLoad(), it means jsonLoad() calls are independent of each other.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

great!

Issue is solved in

https://github.com/test-fullautomation/python-jsonpreprocessor/tree/namsonx/testing/testing_branch

**Comment by HolQue** [comment]
Hi Son,

I have to correct myself: Not great, not solved!

Because of:

https://github.com/test-fullautomation/python-jsonpreprocessor/pull/112#pullrequestreview-1552052301

I added the missing renamings in your code, and now this issue is back!

**Comment by namsonx** [comment]
Hello Holger,

Thank you very much for your finding, it's my mistake.
I had updated the variable name and merged to testing branch as well.

Thank you,
Son

**Comment by HolQue** [comment]
This issue is solved with

https://github.com/test-fullautomation/python-jsonpreprocessor/pull/131

**Comment by HolQue** [comment]
With origin/namsonx/task/stabi_branch (17.08.2023), this issue is back.
Affected: JPP_0506-(COMPOSITE_EXPRESSIONS)-[GOODCASE]

**Comment by HolQue** [comment]
Fixed again in v. 0.3.0
