### ISSUE TITLE
Hint only

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-jsonpreprocessor#99]
When testing the `${}` substitution, it is still possible to get results like:

`variant_numberVAR-${dict_variants.${variant_key_str()}}_MS-${dict_milestones.milestone_key_str(2)}_param`

(instead of `VAR-VARIANT-1_MS-MILESTONE-2_param`)

I wonder why there are still pairs of '`${`' and '`}`' inside.

For me it looks like that the "_substitution finished_" criteria is not proper. Because at end of all substitutions I do not expect any '`${`' any more in the result. Or I expect a syntax error. Or a "_missing parameter_" error.

Maybe something like a "_final validation_" check can be added, an internal check to verify the integrity of the result: In case of any '`${`' can be found, this is an indicator for a failed substitution.

And in case of the expression is a name of a parameter or the name of a dictionary key, at least a "_naming convention_" check should inform about an invalid name (because I would assume, that characters like '`$`' and '`{`' and '`}`' are not allowed inside names).

Both checks together would make sure that the JsonPreprocessor does not return values like above.

**Comment by test-fullautomation** [comment]
@namsonx : What is the status of this issue?

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Son checks.

**Comment by HolQue** [comment]
Test code taken out of JPP_0202, that is successful in between.

Also all other active JPP test cases do not show the described behavior any more.

I would say, the issue can be closed.
